### ISSUE TITLE
Display a notice for matching fields based on previously submitted forms.

### ISSUE THREAD

**Issue by BouncingHitman** [burnacid/MyBB-Form-Creator#118]
**Is your feature request related to a problem? Please describe.**
Well, we deal with a lot of players and end up with loads of cases. Sometimes, when submitting a ban form request for a certain player, you must consider the time you want to ban the player for. Often, you must look at the player's history before making a decision.
**Describe the solution you'd like**
It would be neat if the form could search previously submitted forms with a matching field, and then display a custom notice next to the field on the current form. Sort of like a "username was already taken!" sort of thing.
**Describe alternatives you've considered**
Well, an alternative would be to use the search function of the forums, but who wants to do that when your staff is a bunch of old, non-computer savvy dudes.

**Comment by burnacid** [comment]
Form creator is parsing fields into a template to create a thread, post or pm.
The plugin does not save previous submitted forms to the database.

Your request reqiuers a complete other design of the plugin. Due to this I will have to refuse your feature request.

I know your pain but you need to tell members of your forum not to be so lazy ;) and use the search feature of mybb
